# Generated by Django 3.1.3 on 2020-11-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20201130_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='langs',
            new_name='lang',
        ),
    ]
